### ISSUE TITLE
can not preview your application

### ISSUE THREAD

**Issue by vikbert** [Dan6erbond/Cheeri-No#1]
I did npm installl and npm build. After I start npm run preview, then I got the following error:
`➜ npm run preview

> ~TODO~@0.0.1 preview /Users/zhoux/sites/github/svelte-projects/Cheeri-No
> svelte-kit preview

  SvelteKit v1.0.0-next.107

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network

TypeError: Cannot read property 'user' of undefined`

**Comment by Dan6erbond** [comment]
Thanks for the issue! Fixed in [82c5fd5](https://github.com/Dan6erbond/Cheeri-No/commit/82c5fd593dd49b040d5cdf6b7b87487bb35d7cef). It was an issue with missing authentication on first load.
